<?php
/**
 * ReportExporter — writes complaint summaries as .xlsx (Excel) and .pdf.
 *
 * Both formats are produced in plain PHP, with no libraries or PHP
 * extensions, so the export works on a default XAMPP install:
 *
 *  - XLSX: an Excel file is a ZIP archive of small XML files. We write the
 *    XML ourselves and pack it with a minimal "stored" (uncompressed) ZIP
 *    writer — Excel opens stored ZIPs normally.
 *  - PDF: a PDF is a text-based format of numbered objects. We write pages
 *    of text and lines using the built-in Helvetica font, which every PDF
 *    reader has, so no font files are embedded.
 *
 * Complainants appear by ALIAS only — reports never reveal identities.
 */
class ReportExporter {
    /** Column headers + row values for the complaint list, shared by both formats. */
    const COLUMNS = ['ID', 'Submitted', 'Title', 'Department', 'Category', 'Type', 'Current level', 'Status', 'Severity', 'Complainant'];

    /** Summary groups (title => key in SuperAdmin::reportData()['summary']). */
    const GROUPS = [
        'By status' => 'by_status',
        'By department' => 'by_department',
        'By category' => 'by_category',
        'By current level' => 'by_level',
        'By severity' => 'by_severity',
    ];

    private static function rowValues(array $r) {
        return [
            (int)$r['complaint_id'],
            date('Y-m-d', strtotime($r['created_at'])),
            (string)$r['complaint_title'],
            (string)($r['department'] ?: '—'),
            (string)($r['complaint_category'] ?: 'Uncategorized'),
            $r['complaint_type'] === 'services' ? 'Service' : 'Person',
            workflowLevelLabel($r['current_level']),
            formatStatus($r['status']),
            ucfirst((string)$r['severity']),
            (string)$r['complainant_alias'],
        ];
    }

    /* ==============================================================
     * EXCEL (.xlsx)
     * ============================================================== */

    /** Build the .xlsx file and return its bytes. Two sheets: Summary and Complaints. */
    public static function xlsx(array $report, array $meta) {
        // --- Sheet 1: Summary -------------------------------------
        $summary = [
            [['OSWD Complaint System — Complaint Summary', 1]],
            ['Generated', $meta['generated']],
            ['Generated by', $meta['by']],
            ['Filters', $meta['filters']],
            ['Total complaints', $report['total']],
            [],
        ];
        foreach (self::GROUPS as $title => $key) {
            $summary[] = [[$title, 1], ['Count', 1]];
            foreach ($report['summary'][$key] as $label => $count) {
                $summary[] = [$label, $count];
            }
            $summary[] = [];
        }

        // --- Sheet 2: Complaints ----------------------------------
        $list = [array_map(fn($h) => [$h, 1], self::COLUMNS)];
        foreach ($report['rows'] as $r) {
            $list[] = self::rowValues($r);
        }

        $files = [
            '[Content_Types].xml' => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                . '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
                . '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
                . '<Default Extension="xml" ContentType="application/xml"/>'
                . '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
                . '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
                . '<Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
                . '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
                . '</Types>',
            '_rels/.rels' => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                . '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
                . '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
                . '</Relationships>',
            'xl/workbook.xml' => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                . '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
                . '<sheets><sheet name="Summary" sheetId="1" r:id="rId1"/><sheet name="Complaints" sheetId="2" r:id="rId2"/></sheets>'
                . '</workbook>',
            'xl/_rels/workbook.xml.rels' => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                . '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
                . '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
                . '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/>'
                . '<Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'
                . '</Relationships>',
            // Style 0 = normal, style 1 = bold (headers).
            'xl/styles.xml' => '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                . '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
                . '<fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/></font></fonts>'
                . '<fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills>'
                . '<borders count="1"><border/></borders>'
                . '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>'
                . '<cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/></cellXfs>'
                . '</styleSheet>',
            'xl/worksheets/sheet1.xml' => self::sheetXml($summary, [28, 40]),
            'xl/worksheets/sheet2.xml' => self::sheetXml($list, [7, 12, 40, 12, 30, 9, 22, 14, 10, 18]),
        ];
        return self::zip($files);
    }

    /**
     * One worksheet. Each row is a list of cells; a cell is a value, or
     * [value, 1] for bold. Numbers are written as numbers, text as
     * "inline strings" (so no shared-strings table is needed).
     */
    private static function sheetXml(array $rows, array $widths) {
        $cols = '<cols>';
        foreach ($widths as $i => $w) {
            $cols .= '<col min="' . ($i + 1) . '" max="' . ($i + 1) . '" width="' . $w . '" customWidth="1"/>';
        }
        $cols .= '</cols>';

        $data = '';
        foreach ($rows as $r => $cells) {
            $rowNum = $r + 1;
            $data .= '<row r="' . $rowNum . '">';
            foreach (array_values($cells) as $c => $cell) {
                [$value, $bold] = is_array($cell) ? [$cell[0], 1] : [$cell, 0];
                $ref = self::columnLetter($c) . $rowNum;
                $style = $bold ? ' s="1"' : '';
                if (is_int($value) || is_float($value)) {
                    $data .= '<c r="' . $ref . '"' . $style . '><v>' . $value . '</v></c>';
                } else {
                    $text = htmlspecialchars((string)$value, ENT_XML1 | ENT_QUOTES, 'UTF-8');
                    $data .= '<c r="' . $ref . '"' . $style . ' t="inlineStr"><is><t xml:space="preserve">' . $text . '</t></is></c>';
                }
            }
            $data .= '</row>';
        }

        return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            . '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
            . $cols . '<sheetData>' . $data . '</sheetData></worksheet>';
    }

    /** 0 → A, 25 → Z, 26 → AA ... */
    private static function columnLetter($index) {
        $letters = '';
        for ($n = $index + 1; $n > 0; $n = intdiv($n - 1, 26)) {
            $letters = chr(65 + ($n - 1) % 26) . $letters;
        }
        return $letters;
    }

    /**
     * Minimal ZIP writer ("stored" method = no compression). Format per
     * the PKWARE APPNOTE: a local header + data for each file, then a
     * central directory listing them, then an end-of-directory record.
     */
    private static function zip(array $files) {
        $body = '';
        $central = '';
        $dosTime = ((int)date('H') << 11) | ((int)date('i') << 5) | intdiv((int)date('s'), 2);
        $dosDate = (((int)date('Y') - 1980) << 9) | ((int)date('n') << 5) | (int)date('j');

        foreach ($files as $name => $data) {
            $crc = crc32($data);
            $size = strlen($data);
            $offset = strlen($body);
            $common = pack('vvvvvVVVvv', 20, 0, 0, $dosTime, $dosDate, $crc, $size, $size, strlen($name), 0);

            $body .= pack('V', 0x04034b50) . $common . $name . $data;
            $central .= pack('V', 0x02014b50) . pack('v', 20) . $common
                . pack('vvvVV', 0, 0, 0, 0, $offset) . $name;
        }

        return $body . $central . pack('VvvvvVVv', 0x06054b50, 0, 0, count($files), count($files),
            strlen($central), strlen($body), 0);
    }

    /* ==============================================================
     * PDF
     * ============================================================== */

    // A4 landscape, in PDF points (1/72 inch).
    const PAGE_W = 842;
    const PAGE_H = 595;
    const MARGIN = 36;

    private static $pages = [];     // finished page content streams
    private static $ops = '';       // drawing commands for the current page
    private static $y = 0;          // current vertical position (top-down)

    /** Build the PDF and return its bytes. */
    public static function pdf(array $report, array $meta) {
        self::$pages = [];
        self::$ops = '';
        self::newPage();

        self::text(self::MARGIN, 'OSWD Complaint System - Complaint Summary', 16, true);
        self::$y += 8;
        self::text(self::MARGIN, 'Generated ' . $meta['generated'] . ' by ' . $meta['by'], 9);
        self::text(self::MARGIN, 'Filters: ' . $meta['filters'], 9);
        self::text(self::MARGIN, 'Total complaints: ' . $report['total'], 11, true);
        self::$y += 10;

        // Five small summary tables side by side.
        $groups = self::GROUPS;
        $colW = (self::PAGE_W - 2 * self::MARGIN) / count($groups);
        $top = self::$y;
        $lowest = $top;
        $i = 0;
        foreach ($groups as $title => $key) {
            $x = self::MARGIN + $i++ * $colW;
            self::$y = $top;
            self::text($x, $title, 10, true);
            foreach ($report['summary'][$key] as $label => $count) {
                self::text($x, self::fit($label, $colW - 48, 9), 9, false, false);
                self::text($x + $colW - 40, (string)$count, 9);
            }
            $lowest = max($lowest, self::$y);
        }
        self::$y = $lowest + 16;

        // Complaint list as a table that continues across pages.
        $widths = [34, 58, 160, 44, 130, 40, 104, 66, 48, 66];
        self::tableHeader($widths);
        foreach ($report['rows'] as $r) {
            if (self::$y > self::PAGE_H - self::MARGIN - 14) {
                self::newPage();
                self::tableHeader($widths);
            }
            $x = self::MARGIN;
            foreach (self::rowValues($r) as $c => $value) {
                self::text($x + 2, self::fit((string)$value, $widths[$c] - 4, 8), 8, false, false);
                $x += $widths[$c];
            }
            self::$y += 12;
            self::line(self::MARGIN, self::$y - 9, self::PAGE_W - self::MARGIN, self::$y - 9, 0.85);
        }
        if (!$report['rows']) {
            self::text(self::MARGIN, 'No complaints match these filters.', 9);
        }

        self::$pages[] = self::$ops;
        return self::buildPdf();
    }

    private static function tableHeader(array $widths) {
        $x = self::MARGIN;
        foreach (self::COLUMNS as $c => $title) {
            self::text($x + 2, $title, 8, true, false);
            $x += $widths[$c];
        }
        self::$y += 12;
        self::line(self::MARGIN, self::$y - 9, self::PAGE_W - self::MARGIN, self::$y - 9, 0.2);
    }

    private static function newPage() {
        if (self::$ops !== '') {
            self::$pages[] = self::$ops;
        }
        self::$ops = '';
        self::$y = self::MARGIN;
        // Page number footer.
        $label = 'Page ' . (count(self::$pages) + 1);
        self::$ops .= sprintf("BT /F1 8 Tf %.2F %.2F Td (%s) Tj ET\n",
            self::PAGE_W - self::MARGIN - 40, self::MARGIN / 2, self::escape($label));
    }

    /**
     * Write text at x on the current line. PDF measures y from the BOTTOM
     * of the page, so we convert our top-down position. $advance=false
     * keeps the same line (used for table cells).
     */
    private static function text($x, $string, $size, $bold = false, $advance = true) {
        $baseline = self::PAGE_H - self::$y - $size;
        self::$ops .= sprintf("BT /%s %d Tf %.2F %.2F Td (%s) Tj ET\n",
            $bold ? 'F2' : 'F1', $size, $x, $baseline, self::escape($string));
        if ($advance) {
            self::$y += $size + 4;
        }
    }

    private static function line($x1, $y1, $x2, $y2, $gray) {
        self::$ops .= sprintf("%.2F G 0.5 w %.2F %.2F m %.2F %.2F l S 0 G\n",
            $gray, $x1, self::PAGE_H - $y1, $x2, self::PAGE_H - $y2);
    }

    /** Shorten text to fit a width. Helvetica averages ~0.5 em per character. */
    private static function fit($text, $width, $size) {
        $max = max(3, (int)floor($width / ($size * 0.5)));
        return mb_strlen($text) > $max ? mb_substr($text, 0, $max - 1) . '…' : $text;
    }

    /** Convert to the font's encoding and escape PDF special characters. */
    private static function escape($text) {
        $text = mb_convert_encoding((string)$text, 'Windows-1252', 'UTF-8');
        return strtr($text, ['\\' => '\\\\', '(' => '\\(', ')' => '\\)', "\r" => '', "\n" => ' ']);
    }

    /**
     * Assemble the PDF objects:
     *   1 = catalog, 2 = page tree, 3/4 = Helvetica regular/bold,
     *   then one page object + one content stream per page.
     * The xref table at the end lists each object's byte offset.
     */
    private static function buildPdf() {
        $objects = [];
        $objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
        $objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>';
        $objects[4] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>';

        $kids = [];
        $next = 5;
        foreach (self::$pages as $content) {
            $pageId = $next++;
            $contentId = $next++;
            $kids[] = $pageId . ' 0 R';
            $objects[$pageId] = '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ' . self::PAGE_W . ' ' . self::PAGE_H . ']'
                . ' /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ' . $contentId . ' 0 R >>';
            $objects[$contentId] = '<< /Length ' . strlen($content) . " >>\nstream\n" . $content . "\nendstream";
        }
        $objects[2] = '<< /Type /Pages /Kids [' . implode(' ', $kids) . '] /Count ' . count($kids) . ' >>';
        ksort($objects);

        $pdf = "%PDF-1.4\n";
        $offsets = [];
        foreach ($objects as $id => $body) {
            $offsets[$id] = strlen($pdf);
            $pdf .= $id . " 0 obj\n" . $body . "\nendobj\n";
        }
        $xref = strlen($pdf);
        $pdf .= 'xref' . "\n0 " . (count($objects) + 1) . "\n0000000000 65535 f \n";
        foreach ($offsets as $offset) {
            $pdf .= sprintf("%010d 00000 n \n", $offset);
        }
        $pdf .= 'trailer << /Size ' . (count($objects) + 1) . ' /Root 1 0 R >>' . "\nstartxref\n" . $xref . "\n%%EOF";
        return $pdf;
    }
}
